"""empty message

Revision ID: 0be02fd50fa8
Revises: 632bd63bafea
Create Date: 2022-02-18 13:59:48.816694

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0be02fd50fa8'
down_revision = '632bd63bafea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_staf',
    sa.Column('idstaf', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('kdstaf', sa.String(length=6), nullable=False),
    sa.Column('nmstaf', sa.String(length=75), nullable=False),
    sa.Column('nik', sa.String(length=50), nullable=False),
    sa.Column('tempat_lahir', sa.String(length=30), nullable=False),
    sa.Column('tanggal_lahir', sa.Date(), nullable=True),
    sa.Column('sex', sa.Enum('L', 'P', name='sex'), nullable=False),
    sa.Column('notelp', sa.String(length=15), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('alamat_jalan', sa.String(length=75), nullable=True),
    sa.Column('kabupaten', sa.String(length=50), nullable=True),
    sa.Column('provinsi', sa.String(length=50), server_default='LAMPUNG', nullable=True),
    sa.Column('negara', sa.String(length=50), server_default='INDONESIA', nullable=True),
    sa.Column('tgl_masuk', sa.Date(), nullable=True),
    sa.Column('tgl_berhenti', sa.Date(), nullable=True),
    sa.Column('idjabatan', sa.BigInteger(), server_default='0', nullable=True),
    sa.Column('idunit', sa.BigInteger(), server_default='0', nullable=True),
    sa.Column('idpendidikan', sa.BigInteger(), server_default='0', nullable=True),
    sa.Column('rec_insert', sa.DateTime(), nullable=True),
    sa.Column('rec_update', sa.DateTime(), nullable=True),
    sa.Column('iduser', sa.BigInteger(), server_default='0', nullable=True),
    sa.Column('publish', sa.Enum('T', 'F', name='publish'), server_default='T', nullable=False),
    sa.ForeignKeyConstraint(['idjabatan'], ['tbl_jabatan.idjabatan'], ),
    sa.ForeignKeyConstraint(['idpendidikan'], ['tbl_pendidikan.idpendidikan'], ),
    sa.ForeignKeyConstraint(['idunit'], ['tbl_unit.idunit'], ),
    sa.ForeignKeyConstraint(['iduser'], ['tbl_user.iduser'], ),
    sa.PrimaryKeyConstraint('idstaf')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tbl_staf')
    # ### end Alembic commands ###
