"""empty message

Revision ID: 32f9c2980c78
Revises: 
Create Date: 2022-02-16 13:14:13.579735

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32f9c2980c78'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_armada_jenis',
    sa.Column('idjenis_armada', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('nmjenis_armada', sa.String(length=60), nullable=False),
    sa.Column('publish', sa.Enum('T', 'F', name='publish'), server_default='T', nullable=False),
    sa.PrimaryKeyConstraint('idjenis_armada')
    )
    op.create_table('tbl_barang_kategori',
    sa.Column('idkategori', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('nmkategori', sa.String(length=60), nullable=False),
    sa.Column('publish', sa.Enum('T', 'F', name='publish'), server_default='T', nullable=False),
    sa.PrimaryKeyConstraint('idkategori')
    )
    op.create_table('tbl_barang_satuan',
    sa.Column('idsatuan', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('nmsatuan', sa.String(length=60), nullable=False),
    sa.Column('satuan', sa.String(length=60), nullable=False),
    sa.Column('kilogram', sa.Numeric(precision=10, scale=0), server_default='0', nullable=False),
    sa.Column('publish', sa.Enum('T', 'F', name='publish'), server_default='T', nullable=False),
    sa.PrimaryKeyConstraint('idsatuan')
    )
    op.create_table('tbl_unit',
    sa.Column('idunit', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('nmunit', sa.String(length=60), nullable=False),
    sa.Column('publish', sa.Enum('T', 'F', name='publish'), server_default='T', nullable=False),
    sa.PrimaryKeyConstraint('idunit')
    )
    op.create_table('tbl_user',
    sa.Column('iduser', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=60), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('foto', sa.String(length=255), nullable=False),
    sa.Column('level', sa.Enum('Pelanggan', 'Administrator', 'Manajer', 'Keuangan', 'Gudang', 'SuperAdmin', name='level'), nullable=False),
    sa.Column('publish', sa.Enum('T', 'F', name='publish'), server_default='T', nullable=False),
    sa.PrimaryKeyConstraint('iduser'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tbl_user')
    op.drop_table('tbl_unit')
    op.drop_table('tbl_barang_satuan')
    op.drop_table('tbl_barang_kategori')
    op.drop_table('tbl_armada_jenis')
    # ### end Alembic commands ###
