"""empty message

Revision ID: 563477f79db4
Revises: 0be02fd50fa8
Create Date: 2022-02-18 15:21:56.705741

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '563477f79db4'
down_revision = '0be02fd50fa8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_pelanggan',
    sa.Column('idpelanggan', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('kdpelanggan', sa.String(length=5), nullable=False),
    sa.Column('nmpelanggan', sa.String(length=75), nullable=False),
    sa.Column('notelp', sa.String(length=15), nullable=False),
    sa.Column('email', sa.String(length=60), nullable=False),
    sa.Column('alamat_jalan', sa.String(length=75), nullable=True),
    sa.Column('kabupaten', sa.String(length=50), nullable=True),
    sa.Column('provinsi', sa.String(length=50), server_default='LAMPUNG', nullable=True),
    sa.Column('negara', sa.String(length=50), server_default='INDONESIA', nullable=True),
    sa.Column('deposit', sa.Integer(), server_default='0', nullable=False),
    sa.Column('p_discount', sa.Integer(), server_default='0', nullable=False),
    sa.Column('rec_insert', sa.DateTime(), nullable=True),
    sa.Column('rec_update', sa.DateTime(), nullable=True),
    sa.Column('iduser', sa.BigInteger(), server_default='0', nullable=True),
    sa.Column('publish', sa.Enum('T', 'F', name='publish'), server_default='T', nullable=False),
    sa.ForeignKeyConstraint(['iduser'], ['tbl_user.iduser'], ),
    sa.PrimaryKeyConstraint('idpelanggan')
    )
    op.create_table('tbl_rekening_bank',
    sa.Column('idrekeningbank', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('norekening', sa.String(length=20), nullable=False),
    sa.Column('nmbank', sa.String(length=50), nullable=False),
    sa.Column('cabang', sa.String(length=75), nullable=False),
    sa.Column('nmnasabah', sa.String(length=75), nullable=False),
    sa.Column('rec_insert', sa.DateTime(), nullable=True),
    sa.Column('rec_update', sa.DateTime(), nullable=True),
    sa.Column('iduser', sa.BigInteger(), server_default='0', nullable=True),
    sa.Column('publish', sa.Enum('T', 'F', name='publish'), server_default='T', nullable=False),
    sa.ForeignKeyConstraint(['iduser'], ['tbl_user.iduser'], ),
    sa.PrimaryKeyConstraint('idrekeningbank')
    )
    op.create_table('tbl_armada',
    sa.Column('idarmada', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('kdarmada', sa.String(length=10), nullable=True),
    sa.Column('nomor_plat', sa.String(length=11), nullable=True),
    sa.Column('idjenis_armada', sa.BigInteger(), server_default='0', nullable=True),
    sa.Column('daya_angkut', sa.Integer(), server_default='0', nullable=False),
    sa.Column('nostnk', sa.String(length=30), nullable=True),
    sa.Column('tglpajak', sa.Date(), nullable=True),
    sa.Column('idstaf', sa.BigInteger(), server_default='0', nullable=True),
    sa.Column('kondisi_armada', sa.Enum('BAIK', 'RUSAKRINGAN', 'RUSAKBERAT', 'PERBAIKAN', name='kondisiarmada'), server_default='BAIK', nullable=False),
    sa.Column('publish', sa.Enum('T', 'F', name='publish'), server_default='T', nullable=False),
    sa.ForeignKeyConstraint(['idjenis_armada'], ['tbl_armada_jenis.idjenis_armada'], ),
    sa.ForeignKeyConstraint(['idstaf'], ['tbl_staf.idstaf'], ),
    sa.PrimaryKeyConstraint('idarmada')
    )
    op.create_table('tbl_barang',
    sa.Column('idbarang', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('kdbarang', sa.String(length=10), nullable=False),
    sa.Column('nmbarang', sa.String(length=75), nullable=False),
    sa.Column('merek', sa.String(length=75), nullable=False),
    sa.Column('idkategori', sa.BigInteger(), server_default='0', nullable=True),
    sa.Column('idsatuan', sa.BigInteger(), server_default='0', nullable=True),
    sa.Column('idsupplier', sa.BigInteger(), nullable=False),
    sa.Column('tonase', sa.Integer(), server_default='0', nullable=False),
    sa.Column('harga_net', sa.Integer(), server_default='0', nullable=False),
    sa.Column('harga_jual', sa.Integer(), server_default='0', nullable=False),
    sa.Column('stok', sa.Integer(), server_default='0', nullable=False),
    sa.Column('rec_insert', sa.DateTime(), nullable=True),
    sa.Column('rec_update', sa.DateTime(), nullable=True),
    sa.Column('iduser', sa.BigInteger(), server_default='0', nullable=True),
    sa.Column('publish', sa.Enum('T', 'F', name='publish'), server_default='T', nullable=False),
    sa.ForeignKeyConstraint(['idkategori'], ['tbl_barang_kategori.idkategori'], ),
    sa.ForeignKeyConstraint(['idsatuan'], ['tbl_barang_satuan.idsatuan'], ),
    sa.ForeignKeyConstraint(['idsupplier'], ['tbl_supplier.idsupplier'], ),
    sa.ForeignKeyConstraint(['iduser'], ['tbl_user.iduser'], ),
    sa.PrimaryKeyConstraint('idbarang')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tbl_barang')
    op.drop_table('tbl_armada')
    op.drop_table('tbl_rekening_bank')
    op.drop_table('tbl_pelanggan')
    # ### end Alembic commands ###
