"""empty message

Revision ID: 964768b621e2
Revises: 563477f79db4
Create Date: 2022-02-18 15:33:57.932701

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '964768b621e2'
down_revision = '563477f79db4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tbl_armada')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_armada',
    sa.Column('idarmada', mysql.BIGINT(display_width=20), autoincrement=True, nullable=False),
    sa.Column('kdarmada', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('nomor_plat', mysql.VARCHAR(length=11), nullable=True),
    sa.Column('idjenis_armada', mysql.BIGINT(display_width=20), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('daya_angkut', mysql.INTEGER(display_width=11), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('nostnk', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('tglpajak', sa.DATE(), nullable=True),
    sa.Column('idstaf', mysql.BIGINT(display_width=20), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('kondisi_armada', mysql.ENUM('BAIK', 'RUSAKRINGAN', 'RUSAKBERAT', 'PERBAIKAN'), server_default=sa.text("'BAIK'"), nullable=False),
    sa.Column('publish', mysql.ENUM('T', 'F'), server_default=sa.text("'T'"), nullable=False),
    sa.ForeignKeyConstraint(['idjenis_armada'], ['tbl_armada_jenis.idjenis_armada'], name='tbl_armada_ibfk_1'),
    sa.ForeignKeyConstraint(['idstaf'], ['tbl_staf.idstaf'], name='tbl_armada_ibfk_2'),
    sa.PrimaryKeyConstraint('idarmada'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
