"""empty message

Revision ID: b8012fba161e
Revises: a72d0d6442b6
Create Date: 2022-02-18 13:28:56.562584

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8012fba161e'
down_revision = 'a72d0d6442b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_jabatan',
    sa.Column('idjabatan', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('nmjabatan', sa.String(length=60), nullable=False),
    sa.Column('publish', sa.Enum('T', 'F', name='publish'), server_default='T', nullable=False),
    sa.PrimaryKeyConstraint('idjabatan')
    )
    op.create_table('tbl_metode_bayar',
    sa.Column('idmetode_bayar', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('metode_bayar', sa.String(length=60), nullable=False),
    sa.Column('publish', sa.Enum('T', 'F', name='publish'), server_default='T', nullable=False),
    sa.PrimaryKeyConstraint('idmetode_bayar')
    )
    op.create_table('tbl_pendidikan',
    sa.Column('idpendidikan', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('nmpendidikan', sa.String(length=60), nullable=True),
    sa.Column('alias', sa.String(length=50), nullable=True),
    sa.Column('publish', sa.Enum('T', 'F', name='publish'), server_default='T', nullable=False),
    sa.PrimaryKeyConstraint('idpendidikan')
    )
    op.create_table('tbl_status_bayar',
    sa.Column('idstatus_bayar', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('status_bayar', sa.String(length=30), nullable=False),
    sa.Column('publish', sa.Enum('T', 'F', name='publish'), server_default='T', nullable=False),
    sa.PrimaryKeyConstraint('idstatus_bayar')
    )
    op.create_table('tbl_supplier',
    sa.Column('idsupplier', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('kdsupplier', sa.String(length=5), nullable=False),
    sa.Column('nmsupplier', sa.String(length=75), nullable=False),
    sa.Column('nmperson', sa.String(length=50), nullable=False),
    sa.Column('notelp', sa.String(length=15), nullable=False),
    sa.Column('email', sa.String(length=60), nullable=False),
    sa.Column('alamat_jalan', sa.String(length=75), nullable=True),
    sa.Column('kabupaten', sa.String(length=50), nullable=True),
    sa.Column('provinsi', sa.String(length=50), server_default='LAMPUNG', nullable=True),
    sa.Column('negara', sa.String(length=50), server_default='INDONESIA', nullable=True),
    sa.Column('deposit', sa.Integer(), server_default='0', nullable=False),
    sa.Column('rec_insert', sa.DateTime(), nullable=True),
    sa.Column('rec_update', sa.DateTime(), nullable=True),
    sa.Column('iduser', sa.BigInteger(), nullable=True),
    sa.Column('publish', sa.Enum('T', 'F', name='publish'), server_default='T', nullable=False),
    sa.ForeignKeyConstraint(['iduser'], ['tbl_user.iduser'], ),
    sa.PrimaryKeyConstraint('idsupplier')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tbl_supplier')
    op.drop_table('tbl_status_bayar')
    op.drop_table('tbl_pendidikan')
    op.drop_table('tbl_metode_bayar')
    op.drop_table('tbl_jabatan')
    # ### end Alembic commands ###
