"""empty message

Revision ID: fc9c5f4be600
Revises: 
Create Date: 2022-02-19 11:08:13.867038

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc9c5f4be600'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_armada_jenis',
    sa.Column('idjenis_armada', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('nmjenis_armada', sa.String(length=60), nullable=False),
    sa.Column('publish', sa.Enum('T', 'F', name='publish'), server_default='T', nullable=False),
    sa.PrimaryKeyConstraint('idjenis_armada')
    )
    op.create_table('tbl_barang_kategori',
    sa.Column('idkategori', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('nmkategori', sa.String(length=60), nullable=False),
    sa.Column('publish', sa.Enum('T', 'F', name='publish'), server_default='T', nullable=False),
    sa.PrimaryKeyConstraint('idkategori')
    )
    op.create_table('tbl_barang_satuan',
    sa.Column('idsatuan', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('nmsatuan', sa.String(length=60), nullable=False),
    sa.Column('satuan', sa.String(length=60), nullable=False),
    sa.Column('kilogram', sa.Numeric(precision=10, scale=0), server_default='0', nullable=False),
    sa.Column('publish', sa.Enum('T', 'F', name='publish'), server_default='T', nullable=False),
    sa.PrimaryKeyConstraint('idsatuan')
    )
    op.create_table('tbl_jabatan',
    sa.Column('idjabatan', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('nmjabatan', sa.String(length=60), nullable=False),
    sa.Column('publish', sa.Enum('T', 'F', name='publish'), server_default='T', nullable=False),
    sa.PrimaryKeyConstraint('idjabatan')
    )
    op.create_table('tbl_metode_bayar',
    sa.Column('idmetode_bayar', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('metode_bayar', sa.String(length=60), nullable=False),
    sa.Column('publish', sa.Enum('T', 'F', name='publish'), server_default='T', nullable=False),
    sa.PrimaryKeyConstraint('idmetode_bayar')
    )
    op.create_table('tbl_pendidikan',
    sa.Column('idpendidikan', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('nmpendidikan', sa.String(length=60), nullable=True),
    sa.Column('alias', sa.String(length=50), nullable=True),
    sa.Column('publish', sa.Enum('T', 'F', name='publish'), server_default='T', nullable=False),
    sa.PrimaryKeyConstraint('idpendidikan')
    )
    op.create_table('tbl_status_bayar',
    sa.Column('idstatus_bayar', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('status_bayar', sa.String(length=30), nullable=False),
    sa.Column('publish', sa.Enum('T', 'F', name='publish'), server_default='T', nullable=False),
    sa.PrimaryKeyConstraint('idstatus_bayar')
    )
    op.create_table('tbl_unit',
    sa.Column('idunit', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('nmunit', sa.String(length=60), nullable=False),
    sa.Column('publish', sa.Enum('T', 'F', name='publish'), server_default='T', nullable=False),
    sa.PrimaryKeyConstraint('idunit')
    )
    op.create_table('tbl_user',
    sa.Column('iduser', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=60), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('foto', sa.String(length=255), nullable=False),
    sa.Column('level', sa.Enum('Pelanggan', 'Administrator', 'Manajer', 'Keuangan', 'Gudang', 'SuperAdmin', name='level'), nullable=False),
    sa.Column('publish', sa.Enum('T', 'F', name='publish'), server_default='T', nullable=False),
    sa.PrimaryKeyConstraint('iduser'),
    sa.UniqueConstraint('email')
    )
    op.create_table('tbl_pelanggan',
    sa.Column('idpelanggan', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('kdpelanggan', sa.String(length=5), nullable=False),
    sa.Column('nmpelanggan', sa.String(length=75), nullable=False),
    sa.Column('notelp', sa.String(length=15), nullable=False),
    sa.Column('email', sa.String(length=60), nullable=False),
    sa.Column('alamat_jalan', sa.String(length=75), nullable=True),
    sa.Column('kabupaten', sa.String(length=50), nullable=True),
    sa.Column('provinsi', sa.String(length=50), server_default='LAMPUNG', nullable=True),
    sa.Column('negara', sa.String(length=50), server_default='INDONESIA', nullable=True),
    sa.Column('deposit', sa.Integer(), server_default='0', nullable=False),
    sa.Column('p_discount', sa.Integer(), server_default='0', nullable=False),
    sa.Column('rec_insert', sa.DateTime(), nullable=False),
    sa.Column('rec_update', sa.DateTime(), nullable=True),
    sa.Column('iduser', sa.BigInteger(), server_default='0', nullable=True),
    sa.Column('publish', sa.Enum('T', 'F', name='publish'), server_default='T', nullable=False),
    sa.ForeignKeyConstraint(['iduser'], ['tbl_user.iduser'], ),
    sa.PrimaryKeyConstraint('idpelanggan')
    )
    op.create_table('tbl_rekening_bank',
    sa.Column('idrekeningbank', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('norekening', sa.String(length=20), nullable=False),
    sa.Column('nmbank', sa.String(length=50), nullable=False),
    sa.Column('cabang', sa.String(length=75), nullable=False),
    sa.Column('nmnasabah', sa.String(length=75), nullable=False),
    sa.Column('rec_insert', sa.DateTime(), nullable=False),
    sa.Column('rec_update', sa.DateTime(), nullable=True),
    sa.Column('iduser', sa.BigInteger(), server_default='0', nullable=True),
    sa.Column('publish', sa.Enum('T', 'F', name='publish'), server_default='T', nullable=False),
    sa.ForeignKeyConstraint(['iduser'], ['tbl_user.iduser'], ),
    sa.PrimaryKeyConstraint('idrekeningbank')
    )
    op.create_table('tbl_staf',
    sa.Column('idstaf', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('kdstaf', sa.String(length=6), nullable=False),
    sa.Column('nmstaf', sa.String(length=75), nullable=False),
    sa.Column('nik', sa.String(length=50), nullable=False),
    sa.Column('tempat_lahir', sa.String(length=30), nullable=False),
    sa.Column('tanggal_lahir', sa.Date(), nullable=True),
    sa.Column('sex', sa.Enum('L', 'P', name='sex'), nullable=False),
    sa.Column('notelp', sa.String(length=15), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('alamat_jalan', sa.String(length=75), nullable=True),
    sa.Column('kabupaten', sa.String(length=50), nullable=True),
    sa.Column('provinsi', sa.String(length=50), server_default='LAMPUNG', nullable=True),
    sa.Column('negara', sa.String(length=50), server_default='INDONESIA', nullable=True),
    sa.Column('tgl_masuk', sa.Date(), nullable=True),
    sa.Column('tgl_berhenti', sa.Date(), nullable=True),
    sa.Column('idjabatan', sa.BigInteger(), server_default='0', nullable=True),
    sa.Column('idunit', sa.BigInteger(), server_default='0', nullable=True),
    sa.Column('idpendidikan', sa.BigInteger(), server_default='0', nullable=True),
    sa.Column('rec_insert', sa.DateTime(), nullable=False),
    sa.Column('rec_update', sa.DateTime(), nullable=True),
    sa.Column('iduser', sa.BigInteger(), server_default='0', nullable=True),
    sa.Column('publish', sa.Enum('T', 'F', name='publish'), server_default='T', nullable=False),
    sa.ForeignKeyConstraint(['idjabatan'], ['tbl_jabatan.idjabatan'], ),
    sa.ForeignKeyConstraint(['idpendidikan'], ['tbl_pendidikan.idpendidikan'], ),
    sa.ForeignKeyConstraint(['idunit'], ['tbl_unit.idunit'], ),
    sa.ForeignKeyConstraint(['iduser'], ['tbl_user.iduser'], ),
    sa.PrimaryKeyConstraint('idstaf')
    )
    op.create_table('tbl_supplier',
    sa.Column('idsupplier', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('kdsupplier', sa.String(length=5), nullable=False),
    sa.Column('nmsupplier', sa.String(length=75), nullable=False),
    sa.Column('nmperson', sa.String(length=50), nullable=False),
    sa.Column('notelp', sa.String(length=15), nullable=False),
    sa.Column('email', sa.String(length=60), nullable=False),
    sa.Column('alamat_jalan', sa.String(length=75), nullable=True),
    sa.Column('kabupaten', sa.String(length=50), nullable=True),
    sa.Column('provinsi', sa.String(length=50), server_default='LAMPUNG', nullable=True),
    sa.Column('negara', sa.String(length=50), server_default='INDONESIA', nullable=True),
    sa.Column('deposit', sa.Integer(), server_default='0', nullable=False),
    sa.Column('rec_insert', sa.DateTime(), nullable=False),
    sa.Column('rec_update', sa.DateTime(), nullable=True),
    sa.Column('iduser', sa.BigInteger(), server_default='0', nullable=True),
    sa.Column('publish', sa.Enum('T', 'F', name='publish'), server_default='T', nullable=False),
    sa.ForeignKeyConstraint(['iduser'], ['tbl_user.iduser'], ),
    sa.PrimaryKeyConstraint('idsupplier')
    )
    op.create_table('tbl_armada',
    sa.Column('idarmada', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('kdarmada', sa.String(length=10), nullable=True),
    sa.Column('nomor_plat', sa.String(length=11), nullable=True),
    sa.Column('idjenis_armada', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('daya_angkut', sa.Integer(), server_default='0', nullable=False),
    sa.Column('nostnk', sa.String(length=30), nullable=True),
    sa.Column('tglpajak', sa.Date(), nullable=True),
    sa.Column('idstaf', sa.BigInteger(), server_default='0', nullable=True),
    sa.Column('kondisi_armada', sa.Enum('BAIK', 'RUSAK-RINGAN', 'RUSAK-BERAT', 'PERBAIKAN', name='KondisiArmada'), server_default='BAIK', nullable=False),
    sa.Column('publish', sa.Enum('T', 'F', name='publish'), server_default='T', nullable=False),
    sa.ForeignKeyConstraint(['idjenis_armada'], ['tbl_armada_jenis.idjenis_armada'], ),
    sa.ForeignKeyConstraint(['idstaf'], ['tbl_staf.idstaf'], ),
    sa.PrimaryKeyConstraint('idarmada')
    )
    op.create_table('tbl_barang',
    sa.Column('idbarang', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('kdbarang', sa.String(length=10), nullable=False),
    sa.Column('nmbarang', sa.String(length=75), nullable=False),
    sa.Column('merek', sa.String(length=75), nullable=False),
    sa.Column('idkategori', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('idsatuan', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('idsupplier', sa.BigInteger(), nullable=False),
    sa.Column('tonase', sa.Integer(), server_default='0', nullable=False),
    sa.Column('harga_net', sa.Integer(), server_default='0', nullable=False),
    sa.Column('harga_jual', sa.Integer(), server_default='0', nullable=False),
    sa.Column('stok', sa.Integer(), server_default='0', nullable=False),
    sa.Column('rec_insert', sa.DateTime(), nullable=False),
    sa.Column('rec_update', sa.DateTime(), nullable=True),
    sa.Column('iduser', sa.BigInteger(), server_default='0', nullable=True),
    sa.Column('publish', sa.Enum('T', 'F', name='publish'), server_default='T', nullable=False),
    sa.ForeignKeyConstraint(['idkategori'], ['tbl_barang_kategori.idkategori'], ),
    sa.ForeignKeyConstraint(['idsatuan'], ['tbl_barang_satuan.idsatuan'], ),
    sa.ForeignKeyConstraint(['idsupplier'], ['tbl_supplier.idsupplier'], ),
    sa.ForeignKeyConstraint(['iduser'], ['tbl_user.iduser'], ),
    sa.PrimaryKeyConstraint('idbarang')
    )
    op.create_table('tbl_transaksi_penjualan',
    sa.Column('idt_penjualan', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('nofaktur', sa.String(length=13), nullable=False),
    sa.Column('tgl_transaksi', sa.Date(), nullable=False),
    sa.Column('iduser', sa.BigInteger(), nullable=False),
    sa.Column('idpelanggan', sa.BigInteger(), nullable=False),
    sa.Column('keterangan', sa.String(length=255), nullable=True),
    sa.Column('total', sa.Integer(), server_default='0', nullable=False),
    sa.Column('jenis_do', sa.Enum('TAKEIT', 'DELIVERY', 'KURIR'), server_default='TAKEIT', nullable=False),
    sa.Column('rec_insert', sa.DateTime(), nullable=False),
    sa.Column('rec_update', sa.DateTime(), nullable=True),
    sa.Column('rec_delete', sa.DateTime(), nullable=True),
    sa.Column('status_delete', sa.Enum('1', '0', name='StatusDelete'), server_default='0', nullable=False),
    sa.Column('delay', sa.Enum('T', 'F', name='publish'), server_default='F', nullable=False),
    sa.Column('publish', sa.Enum('T', 'F', name='publish'), server_default='T', nullable=False),
    sa.ForeignKeyConstraint(['idpelanggan'], ['tbl_pelanggan.idpelanggan'], ),
    sa.ForeignKeyConstraint(['iduser'], ['tbl_user.iduser'], ),
    sa.PrimaryKeyConstraint('idt_penjualan')
    )
    op.create_table('tbl_transaksi_penjualan_detail',
    sa.Column('idtd_penjualan', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('idt_penjualan', sa.BigInteger(), nullable=False),
    sa.Column('idbarang', sa.BigInteger(), nullable=False),
    sa.Column('harga_jual', sa.Integer(), server_default='0', nullable=False),
    sa.Column('qty', sa.Integer(), server_default='0', nullable=False),
    sa.Column('tonase', sa.Integer(), server_default='0', nullable=False),
    sa.Column('discount', sa.Integer(), server_default='0', nullable=False),
    sa.Column('iduser', sa.BigInteger(), nullable=False),
    sa.Column('rec_insert', sa.DateTime(), nullable=False),
    sa.Column('rec_update', sa.DateTime(), nullable=True),
    sa.Column('publish', sa.Enum('T', 'F', name='publish'), server_default='T', nullable=False),
    sa.ForeignKeyConstraint(['idbarang'], ['tbl_barang.idbarang'], ),
    sa.ForeignKeyConstraint(['idt_penjualan'], ['tbl_transaksi_penjualan.idt_penjualan'], ),
    sa.ForeignKeyConstraint(['iduser'], ['tbl_user.iduser'], ),
    sa.PrimaryKeyConstraint('idtd_penjualan')
    )
    op.create_table('tbl_transaksi_penjualan_pembayaran',
    sa.Column('idtp_penjualan', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('kdtp_penjualan', sa.String(length=13), nullable=True),
    sa.Column('idt_penjualan', sa.BigInteger(), nullable=False),
    sa.Column('tgl_pembayaran', sa.Date(), nullable=False),
    sa.Column('idmetode_bayar', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('idrekeningbank', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('keterangan', sa.String(length=255), nullable=True),
    sa.Column('total', sa.Integer(), server_default='0', nullable=False),
    sa.Column('idstatus_bayar', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('iduser', sa.BigInteger(), nullable=False),
    sa.Column('rec_insert', sa.DateTime(), nullable=False),
    sa.Column('rec_update', sa.DateTime(), nullable=True),
    sa.Column('rec_delete', sa.DateTime(), nullable=True),
    sa.Column('status_delete', sa.Enum('1', '0', name='StatusDelete'), server_default='0', nullable=False),
    sa.Column('publish', sa.Enum('T', 'F', name='publish'), server_default='T', nullable=False),
    sa.ForeignKeyConstraint(['idmetode_bayar'], ['tbl_metode_bayar.idmetode_bayar'], ),
    sa.ForeignKeyConstraint(['idrekeningbank'], ['tbl_rekening_bank.idrekeningbank'], ),
    sa.ForeignKeyConstraint(['idstatus_bayar'], ['tbl_status_bayar.idstatus_bayar'], ),
    sa.ForeignKeyConstraint(['idt_penjualan'], ['tbl_transaksi_penjualan.idt_penjualan'], ),
    sa.ForeignKeyConstraint(['iduser'], ['tbl_user.iduser'], ),
    sa.PrimaryKeyConstraint('idtp_penjualan')
    )
    op.create_table('tbl_transaksi_penjualan_do',
    sa.Column('idtpdo_penjualan', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('kdtpdo_penjualan', sa.String(length=13), nullable=True),
    sa.Column('idtp_penjualan', sa.BigInteger(), nullable=False),
    sa.Column('idt_penjualan', sa.BigInteger(), nullable=False),
    sa.Column('tgl_buat', sa.DateTime(), nullable=False),
    sa.Column('tgl_kirim', sa.DateTime(), nullable=True),
    sa.Column('tgl_tiba', sa.DateTime(), nullable=True),
    sa.Column('nmpenerima', sa.String(length=75), nullable=True),
    sa.Column('notelp', sa.String(length=15), nullable=True),
    sa.Column('email', sa.String(length=60), nullable=True),
    sa.Column('alamat_jalan', sa.String(length=75), nullable=True),
    sa.Column('kabupaten', sa.String(length=50), nullable=True),
    sa.Column('provinsi', sa.String(length=50), server_default='LAMPUNG', nullable=True),
    sa.Column('negara', sa.String(length=50), server_default='INDONESIA', nullable=True),
    sa.Column('idarmada', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('status_do', sa.Enum('LETTER', 'LOADING', 'DELIVERY', 'ARRIVE', 'RETURN'), server_default='LETTER', nullable=False),
    sa.Column('keterangan', sa.String(length=255), nullable=True),
    sa.Column('iduser', sa.BigInteger(), nullable=False),
    sa.Column('rec_insert', sa.DateTime(), nullable=False),
    sa.Column('rec_update', sa.DateTime(), nullable=True),
    sa.Column('rec_delete', sa.DateTime(), nullable=True),
    sa.Column('status_delete', sa.Enum('1', '0', name='StatusDelete'), server_default='0', nullable=False),
    sa.Column('publish', sa.Enum('T', 'F', name='publish'), server_default='T', nullable=False),
    sa.ForeignKeyConstraint(['idarmada'], ['tbl_armada.idarmada'], ),
    sa.ForeignKeyConstraint(['idt_penjualan'], ['tbl_transaksi_penjualan.idt_penjualan'], ),
    sa.ForeignKeyConstraint(['idtp_penjualan'], ['tbl_transaksi_penjualan_pembayaran.idtp_penjualan'], ),
    sa.ForeignKeyConstraint(['iduser'], ['tbl_user.iduser'], ),
    sa.PrimaryKeyConstraint('idtpdo_penjualan')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tbl_transaksi_penjualan_do')
    op.drop_table('tbl_transaksi_penjualan_pembayaran')
    op.drop_table('tbl_transaksi_penjualan_detail')
    op.drop_table('tbl_transaksi_penjualan')
    op.drop_table('tbl_barang')
    op.drop_table('tbl_armada')
    op.drop_table('tbl_supplier')
    op.drop_table('tbl_staf')
    op.drop_table('tbl_rekening_bank')
    op.drop_table('tbl_pelanggan')
    op.drop_table('tbl_user')
    op.drop_table('tbl_unit')
    op.drop_table('tbl_status_bayar')
    op.drop_table('tbl_pendidikan')
    op.drop_table('tbl_metode_bayar')
    op.drop_table('tbl_jabatan')
    op.drop_table('tbl_barang_satuan')
    op.drop_table('tbl_barang_kategori')
    op.drop_table('tbl_armada_jenis')
    # ### end Alembic commands ###
